### ISSUE TITLE
[BUG] After running on monitor with different resolution, configuration window is unusable

### ISSUE THREAD

**Issue by fre-sch** [TinusHeystek/New-World-Minimap-Aeternum-Cartogram#1]
After running on monitor #1 with resolution 3840x2160, and then running on monitor #2 at 2560x1440, the settings window is not completely usable.
![image](https://user-images.githubusercontent.com/282692/202903177-c8e4d264-2982-486a-85d4-35263811d8f3.png)

**Comment by TinusHeystek** [comment]
Hi, @fre-sch, please use the new Windowed Mode feature.

**Comment by TinusHeystek** [comment]
Hi, @fre-sch, please use the new Windowed Mode feature.

**Comment by fre-sch** [comment]
As you can see in the screenshot, the tabs aren't visible/reachable. And since the tabs aren't visible/reachable, neither is the checkbox for switching to window mode.

**Comment by TinusHeystek** [comment]
Hi @fre-sch just delete the Settings.json file to reset everything.

**Comment by fre-sch** [comment]
Where is this Settings.json file located? Is it this one `New World - Aeternum Cartogram\AeternumCartogram_Data\StreamingAssets\Settings.json`?

I realize this is most likely a very rare issue, possibly one only I have. I sometimes play on my desk, sometimes I play on a TV. So in the end, no matter how I position the minimap and configuration window, it'll never be right for one of them.  There being a Settings.json, I can switch those out depending on the display I play on. I know Cartogram already supports profiles, but that's just for the game position recognition. Without access to the main configuration window, profiles wouldn't help in this case because they're potentially offscreen.

If this was something I need to fix, I guess I would implement some checks on startup:
- Is the configured size (map or configuration window) larger than the screen area? Clamp it, probably even clamp to 50% of area.
- Is the configured position (just configuration window) outside the screen area? Clamp it to center of screen area.
- possibly save and restore position and size of minimap and configuration window per display hardware identifier.
- include map and configuration window sizes in profiles, and have a profile switch keybinding
- make configuration window draggable by clicking anywhere, not just the dedicated button in its titlebar

**Comment by fre-sch** [comment]
Here's a batch script to enable applying versions of Settings.json. One version of this batch file per Settings.json must be created. `INSTALLATION_DIRECTORY` must be replaced with actual absolute path to directory of "New World - Aeternum Cartogram".

- In `AeternumCartogram_Data\StreamingAssets\` create `Settings.1.json` or create a copy of Settings.json and rename to `Settings.1.json`.
- Create a batch file `Start Settings 1.bat` with contents below inside `New World - Aeternum Cartogram` directory to apply `Settings.1.json`
- Starting `Start Settings 1.bat` will first apply `Settings.1.json`, then start AeternumCartogram.
- Repeat above steps as necessary, by creating additional `Settings.X.json` files and additional `Start Settings X.bat` files.

```batch
@echo off
cd "INSTALLATION_DIRECTORY"
del "AeternumCartogram_Data\StreamingAssets\Settings.json"
mklink /H "AeternumCartogram_Data\StreamingAssets\Settings.json" "AeternumCartogram_Data\StreamingAssets\Settings.1.json"
start AeternumCartogram.exe
```

An unexpected benefit of using hardlinks instead of copying, means settings made while running AeternumCartogram will actually persist for settings file applied.
